# Generated by Django 3.0.4 on 2020-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20200314_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='body',
            field=models.TextField(db_index=True),
        ),
    ]
