# Generated by Django 3.0.4 on 2020-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20200315_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(db_index=True, default='tmp', max_length=150),
        ),
    ]
