# Generated by Django 3.0.4 on 2020-03-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20200320_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image3',
        ),
    ]
